spring:
  config:
    import: application-secret.yml
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE.ENDPOINT_URL.dev}:5432/postgres?currentSchema=${DATABASE.NAME.dev}
    username: ${DATABASE.USERNAME.dev}
    password: ${DATABASE.PASSWORD.dev}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        auto_quote_keyword: true
  data:
    redis:
      host: redis
      port: 6379

logging:
  level:
    org.hibernate.SQL: debug
  slack:
    webhook_url: ${SLACK.WEBHOOK_URL.dev}
    config: classpath:logback-spring.xml

jwt:
  secret:
    ${JWT.SECRET}

aws-property:
  access-key: ${AWS_PROPERTY.ACCESS_KEY}
  secret-key: ${AWS_PROPERTY.SECRET_KEY}
  bucket: ${AWS_PROPERTY.BUCKET}
  aws-region: ap-northeast-2
  s3-url: ${AWS_PROPERTY.S3_URL}