spring:
  config:
    import: application-secret.yml
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE.ENDPOINT_URL.prod}:5432/postgres?currentSchema=${DATABASE.NAME.prod}
    username: ${DATABASE.USERNAME.prod}
    password: ${DATABASE.PASSWORD.prod}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        auto_quote_keyword: true
  data:
    redis:
      host: ${REDIS.host}
      port: 6379
  task:
    scheduling:
      pool:
        size: 1
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL.username.prod}
    password: ${MAIL.password.prod}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.hibernate.SQL: debug
  slack:
    webhook_url: ${SLACK.WEBHOOK_URL.prod}
    config: classpath:logback-spring.xml

jwt:
  secret:
    ${JWT.SECRET}
  access-token-expire-time:
    ${JWT.EXPIRE_ACCESS}
  refresh-token-expire-time:
    ${JWT.EXPIRE_REFRESH}

aws-property:
  access-key: ${AWS_PROPERTY.ACCESS_KEY.prod}
  secret-key: ${AWS_PROPERTY.SECRET_KEY.prod}
  bucket: ${AWS_PROPERTY.BUCKET.prod}
  aws-region: ap-northeast-2
  s3-url: ${AWS_PROPERTY.S3_URL.prod}
