name: CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: create application-secret.yml
        run: |
          # create application-secret.yml
          cd ./src/main/resources
          
          # application-secret.yml 파일 생성
          touch ./application-secret.yml
          
          # GitHub-Actions 에서 설정한 값을 application-secret.yml 파일에 쓰기..git
          echo "${{ secrets.CI_APPLICATION_SECRET }}" >> ./application-secret.yml
          
          # application.yml 파일 확인
          cat ./application-secret.yml
        shell: bash

      - name: build
        run: |
          chmod +x gradlew
          ./gradlew build -x test
        shell: bash